name: Flutter iOS Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release IPA
    runs-on: macos-latest
    steps:
      - name: Print current directory
        run: pwd

      - name: List files in current directory
        run: ls -la
