name: Flutter iOS Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release APK
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"

      - name: check xcode and clang version
        run: |
          xcodebuild -version
          clang --version

      - name: flutter pub get
        run: flutter pub get

      - name: Fastlane Match setup
        run: |
          cd ios
          fastlane dev

      - name: flutter build iOS
        run: flutter build ios --release --flavor dev -t lib/main_dev.dart

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS-release
          path: build/ios/iphoneos/Runner.app
