name: Flutter iOS Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release IPA
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.3.0"

      - name: Check Xcode and Clang version
        run: |
          xcodebuild -version
          clang --version

      - name: Flutter Pub Get
        run: flutter pub get
        working-directory: ./

      - name: Fastlane Match Setup
        run: |
          cd ios
          fastlane dev

      - name: Flutter Build iOS
        run: flutter build ios --release --flavor dev -t lib/main_dev.dart
        working-directory: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS-release
          path: build/ios/iphoneos/Runner.app
        working-directory: ./
